#!/usr/bin/env python3
"""Draw the application icon and write every size the desktops ask for.

Run this only when the artwork changes - the generated files are committed, so
neither installing nor building needs Pillow:

    python packaging/make_icons.py

Outputs into ``EasyMode/lgtv_easy/assets/`` (inside the package, so the running
app finds them the same way whether it was started from source, installed with
pip, or frozen into an .exe):

    icon.ico            multi-resolution Windows icon (16 -> 256)
    icon.png            512px master, used as the generic PNG
    icon-<N>.png        one per hicolor icon-theme size, for Linux
    icon.svg            hand-written vector twin, for scalable/ on Linux

The artwork: a white TV on a blue rounded square, with a crescent moon punched
*through* the screen so the background shows in it. Everything is a solid shape
- no thin strokes, no gradients inside the glyph - because the icon has to stay
legible at 16px in a Windows taskbar, where hairlines disappear.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - developer tool
    sys.exit("This script needs Pillow:  python -m pip install pillow")

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "EasyMode" / "lgtv_easy" / "assets"

# Sizes Windows packs into an .ico, and the hicolor theme dirs Linux installs to.
ICO_SIZES = [16, 20, 24, 32, 40, 48, 64, 128, 256]
PNG_SIZES = [16, 22, 24, 32, 48, 64, 128, 256, 512]

# Supersampling factor: draw big, shrink with LANCZOS. Cheaper than hand-hinting
# each size and it keeps the curves clean down to 16px.
SS = 8

BG_TOP = (110, 155, 255)      # #6E9BFF
BG_BOTTOM = (59, 98, 217)     # #3B62D9
WHITE = (255, 255, 255)

# Geometry in fractions of the canvas, so one description drives every size.
CORNER = 0.215                # rounded-square radius of the tile
TV = (0.135, 0.190, 0.865, 0.660)   # screen body: left, top, right, bottom
TV_R = 0.070                  # its corner radius
NECK = (0.455, 0.660, 0.545, 0.730)  # stand neck
BASE = (0.310, 0.730, 0.690, 0.795)  # stand foot
BASE_R = 0.030
MOON_OUT = (0.500, 0.425, 0.150)     # cx, cy, r  - the moon's disc
MOON_CUT = (0.573, 0.372, 0.132)     # cx, cy, r  - bitten out of it


def _gradient(size: int) -> "Image.Image":
    """Vertical blue gradient the tile is filled with."""
    img = Image.new("RGB", (1, size))
    px = img.load()
    for y in range(size):
        t = y / max(1, size - 1)
        px[0, y] = tuple(round(a + (b - a) * t) for a, b in zip(BG_TOP, BG_BOTTOM))
    return img.resize((size, size), Image.NEAREST)


def _rounded_mask(size: int, box, radius: float) -> "Image.Image":
    mask = Image.new("L", (size, size), 0)
    d = ImageDraw.Draw(mask)
    x0, y0, x1, y1 = (v * size for v in box)
    d.rounded_rectangle((x0, y0, x1, y1), radius=radius * size, fill=255)
    return mask


def render(size: int) -> "Image.Image":
    """One finished RGBA icon at ``size`` pixels."""
    n = size * SS

    # 1. The tile: blue gradient clipped to a rounded square.
    tile = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    tile.paste(_gradient(n), (0, 0), _rounded_mask(n, (0, 0, 1, 1), CORNER))

    # 2. The white glyph, built as a single mask so the moon can be a real hole
    #    in it rather than a lighter shape painted on top.
    glyph = Image.new("L", (n, n), 0)
    g = ImageDraw.Draw(glyph)
    g.rounded_rectangle([v * n for v in TV], radius=TV_R * n, fill=255)
    g.rectangle([v * n for v in NECK], fill=255)
    g.rounded_rectangle([v * n for v in BASE], radius=BASE_R * n, fill=255)

    def circle(draw, spec, fill):
        cx, cy, r = (v * n for v in spec)
        draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=fill)

    circle(g, MOON_OUT, 0)     # punch the disc out of the screen...
    circle(g, MOON_CUT, 255)   # ...then fill part of it back: a crescent hole

    tile.paste(Image.new("RGBA", (n, n), WHITE + (255,)), (0, 0), glyph)
    return tile.resize((size, size), Image.LANCZOS)


SVG = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by packaging/make_icons.py - edit that, not this. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#6E9BFF"/>
      <stop offset="1" stop-color="#3B62D9"/>
    </linearGradient>
    <mask id="glyph">
      <rect x="0" y="0" width="512" height="512" fill="black"/>
      <rect x="{tvx}" y="{tvy}" width="{tvw}" height="{tvh}" rx="{tvr}" fill="white"/>
      <rect x="{nx}" y="{ny}" width="{nw}" height="{nh}" fill="white"/>
      <rect x="{bx}" y="{by}" width="{bw}" height="{bh}" rx="{br}" fill="white"/>
      <circle cx="{mox}" cy="{moy}" r="{mor}" fill="black"/>
      <circle cx="{mcx}" cy="{mcy}" r="{mcr}" fill="white"/>
    </mask>
  </defs>
  <rect x="0" y="0" width="512" height="512" rx="{corner}" fill="url(#tile)"/>
  <rect x="0" y="0" width="512" height="512" fill="#FFFFFF" mask="url(#glyph)"/>
</svg>
"""


def svg_text() -> str:
    def s(v):  # fraction -> 512-space, trimmed
        return f"{v * 512:g}"
    return SVG.format(
        corner=s(CORNER),
        tvx=s(TV[0]), tvy=s(TV[1]), tvw=s(TV[2] - TV[0]), tvh=s(TV[3] - TV[1]),
        tvr=s(TV_R),
        nx=s(NECK[0]), ny=s(NECK[1]), nw=s(NECK[2] - NECK[0]),
        nh=s(NECK[3] - NECK[1]),
        bx=s(BASE[0]), by=s(BASE[1]), bw=s(BASE[2] - BASE[0]),
        bh=s(BASE[3] - BASE[1]), br=s(BASE_R),
        mox=s(MOON_OUT[0]), moy=s(MOON_OUT[1]), mor=s(MOON_OUT[2]),
        mcx=s(MOON_CUT[0]), mcy=s(MOON_CUT[1]), mcr=s(MOON_CUT[2]),
    )


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    images = {n: render(n) for n in sorted(set(ICO_SIZES + PNG_SIZES))}

    for n in PNG_SIZES:
        images[n].save(OUT / f"icon-{n}.png")
    images[512].save(OUT / "icon.png")
    # Pillow builds the whole multi-resolution .ico from the 256px master.
    images[256].save(OUT / "icon.ico",
                     sizes=[(n, n) for n in ICO_SIZES])
    (OUT / "icon.svg").write_text(svg_text(), encoding="utf-8")

    written = sorted(p.name for p in OUT.iterdir())
    print(f"wrote {len(written)} files to {OUT}:")
    print("  " + "  ".join(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
